networks:
  btc-tracker-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  btc-tracker:
    build:
      context: .
    volumes:
      - ./data:/app/data
    networks:
      - btc-tracker-net
    restart: unless-stopped